### ISSUE TITLE
微信创建支付返回值错误

### ISSUE THREAD

**Issue by aslanTT** [leancloud/weapp-pay-getting-started#2]
如图，创建微信支付，err和result打出来均为null
求教

![screen shot 2017-02-14 at 12 20 44 pm](https://cloud.githubusercontent.com/assets/1904655/22915194/640cc264-f2b0-11e6-8a88-116588b03240.png)

**Comment by aslanTT** [comment]
wxpay.js里有引用weixin-pay，但我没这个js文件呢

**Comment by leeyeh** [comment]
>wxpay.js里有引用weixin-pay，但我没这个js文件呢

https://github.com/tvrcgo/weixin-pay

**Comment by aslanTT** [comment]
@leeyeh 我找到了这个文件。但是demo跑起来这里打印出来都是null为啥呢

**Comment by leeyeh** [comment]
我并不是 https://github.com/tvrcgo/weixin-pay 的作者，如果这个库有问题我建议到这个库提 issue。

这个 Demo 中这个 API 能够正确的返回 result，你可以先检查一下传的参数是否都符合要求。还有就是 `WEIXIN_PAY_SECRET` 是否配置正确。

**Comment by aslanTT** [comment]
@leeyeh 这些在后台我都配了，是正确的

**Comment by aslanTT** [comment]
成功了，我的问题，price字段赋错了。
